import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { LanguageProvider } from "./_Components/UserProvider";
import LanguageSwitcher from "./_Components/language";
import Footer from "./_Components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <section className="min-h-screen bg-gradient-to-b from-purple-900 via-black to-gray-900  text-white flex flex-col items-center">
            <div className="bg-purple-900 h-16 w-full">
              <div className="w-full flex justify-center right-10 md:right-0  py-5 space-x-3 md:space-x-6 text-md md:text-xl font-light z-10">
                <Link href="/">
                  <button
                    type="button"
                    className="hover:underline decoration-purple-300"
                  >
                    Home
                  </button>
                </Link>
                <Link href="/about">
                  <button type="button" className="hover:underline">
                    About
                  </button>
                </Link>
                <Link href="/projects">
                  <button type="button" className="hover:underline">
                    Projects
                  </button>
                </Link>
                {/* <Link href="/contact">
                  <button type="button" className="hover:underline">
                    Contact
                  </button>
                </Link> */}
                <Link href="/skills">
                  <button type="button" className="hover:underline">
                    Skills
                  </button>
                </Link>
              </div>
              <div>
                <LanguageSwitcher />
              </div>
            </div>

            <div className="flex-grow flex justify-center items-center w-full">
              {children}
            </div>
            <Footer />
          </section>
        </LanguageProvider>
      </body>
    </html>
  );
}
